steps:
- id: Build Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build --target ${_ENV} --build-arg USERNAME=${_USERNAME} --network cloudbuild -t ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_ENV} .']
- id: Push Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_ENV}']
substitutions:
  _LOCATION: europe-north1
  _REPOSITORY: bf-data-apps-images
  _IMAGE: example-airflow-task-repo
  _USERNAME: prod-user
  _ENV: prod
