version: '3'

services:
  app:
    image: <your-image-name>
    command: ["python","src/task.py"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/localtest/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ./src:/home/localtest/src
      - ${GOOGLE_APPLICATION_CREDENTIALS_PATH}:/home/localtest/.config/gcloud

